api_encryption_key: ENC[AES256_GCM,data:C1RfRFcRm0+t+5ox2l8LcdcikH4XfhyTzHPvlPkMJNQF+hcc6lZCpNpjPrk=,iv:bLwYfLXWp2PT5DYWTrarse2cKhAy1zHOw6IOpD212As=,tag:r2wlgKZk6cVinrMq+zcozA==,type:str]
ota_password: ENC[AES256_GCM,data:k+1pCAQZVNxsftQ2J3oH3w==,iv:2T4TsaqYS4vYL+Iyxp9QXjYUUt3ALc2nJk4fHCGWNLE=,tag:YkgAJ5qjB8bydf2m/IGPBQ==,type:str]
wifi_ssid: ENC[AES256_GCM,data:kZcr8+Knau2jeQaNGebo8MM=,iv:+W+g6xrgtWIQRtxepx30OUnrBGE/9ICaeRBq4MdNXD8=,tag:bBLZsB8FQF5Uk3yh2ORGMA==,type:str]
wifi_password: ENC[AES256_GCM,data:Hz7Smeri1bv77hWCN7HM0GtC/XDHlcRdcQs=,iv:fTeAj77AHJzxi/W25S6a5DKt4cKS3NMA+emEMgG12Fw=,tag:qmMCr+L9FLUeFb/CPc3ulg==,type:str]
led_node_2_ip: ENC[AES256_GCM,data:y5mmoFMjgJRACg==,iv:k/ALSjKk6plzPvZZrBiPOYoMyf5JSlgMg34wLUjoG1g=,tag:WkWrxMxCcjSyd/yaSoTSDQ==,type:str]
ir_blaster_ip: ENC[AES256_GCM,data:dqIxa/I5XG+SmQ==,iv:UiAxLkCKf1XstlvTFirnzB2WBkfjHn5ARb+pYjY9nxc=,tag:7k0L28Uk90pUbqlk5+1v7w==,type:str]
ir_blaster_2_ip: ENC[AES256_GCM,data:7M56sLD/c/ddEQ==,iv:sB3yIUNUL6uOvmBGjFQv/pWjGjBBLXlILVQlhRz2l9w=,tag:TnSbY9BsEG5CI7E3ql42/A==,type:str]
ir_blaster_3_ip: ENC[AES256_GCM,data:9uSX+fx7l3gN,iv:o9JwY/naK76qhe8RTVZjw1FN8oN832+u+sfXy2f177o=,tag:QY3DWWHTzL4N6qEIFp9Nfg==,type:str]
led_dimmer_node_1: ENC[AES256_GCM,data:gERyxPQue1APTg==,iv:ir8nb70BaHtOg86F3Mt9Je/v0wFEhIwg2Ndmn1SaAhg=,tag:ByHNcUwWwiPxtxsfHdKZ/w==,type:str]
artnet_local_ip: ENC[AES256_GCM,data:Ri8kLQye2XEIXQ==,iv:82xCcWAB/SIqeDGvuQOreJ7PYXZRUlIv0uVG8Gnl/nQ=,tag:4hUMtRi6AVgrULA8tiwuag==,type:str]
moisture_sensor_1_ip: ENC[AES256_GCM,data:/OEUPD92A0vG,iv:Zrtx18Yjaz3BHNOxCfJjqtQb5whrTK8IhgSAmNuQ0hc=,tag:hUnyWbil7BYNS2RgOJA9Pg==,type:str]
metronome_ip: ENC[AES256_GCM,data:1WnJAXVf37bi1A==,iv:3PBzFEkPSbP3uArc/gpk1+/INjPJHdD7zh5/UP6XMlo=,tag:+3fweJEEjDMnxhy3HYo7ZQ==,type:str]
pixel_hotspot_ssid: ENC[AES256_GCM,data:ev+PtZtPNgljzA==,iv:NwjtOeGQcsIusu14PBkfAc/XlVcKiS7jmbjdEj49LBw=,tag:/MrcN8xJaRnonPrxZHPCYQ==,type:str]
pixel_hotspot_password: ENC[AES256_GCM,data:5T1YqIhrv0JS0E90,iv:93e0GGZUBykdqFKAiRsbDX9KXXRyS30KxtPvMallxSU=,tag:jzR2q8aaAOWh8VxL5EF8AA==,type:str]
travel_router_ssid: ENC[AES256_GCM,data:Ecr+k2xNQztefLME5vYv0Oc=,iv:U4ITLiy+wqWRKTI/dBH0zEazgIdtrYfN52gInb2C84A=,tag:WkKfADlZ9PCZVL0fJTvZ3Q==,type:str]
travel_router_password: ENC[AES256_GCM,data:Uded6tLX0ePd10BUNXQ=,iv:NNBIsoQPitECWFi9nUvAUGfj86nG2BO2XZj5Gy2R4/Q=,tag:hZo6EQQelWs/riyXjxXKpw==,type:str]
zhenya_hotspot_ssid: ENC[AES256_GCM,data:qku7IOY=,iv:fPKgIA/xfwTPa2r0rcqGsMpQDuX2t+9zJc1/gPokpyY=,tag:P6KXmX2PnrZ77x1DYso0tQ==,type:str]
zhenya_hotspot_password: ENC[AES256_GCM,data:/UoChtFalJgqRZwE,iv:7T6qMBaqEGG3louhtQJ4R9fEKnUrcG4J2Xs1ASna868=,tag:jwm4mke4ktRmdpKfyEtpvQ==,type:str]
web_server_username: ENC[AES256_GCM,data:ysyMc8E=,iv:HHEYJh+T1YKImepSSPaJFoY/nHn6uLm2hyVaX7V+lHo=,tag:5rKD1fJulOaUE6eBPig2Mw==,type:str]
web_server_password: ENC[AES256_GCM,data:/liJaE8KLoWzG5YjyN6VNwJS,iv:2VwT3SXwnIM2XC/sc4AKJAtQqYO/RrS7qrq3yx49snc=,tag:yiM0Fe+PuRDBcxjJXqCN1g==,type:str]
sops:
    lastmodified: "2025-11-11T02:27:11Z"
    mac: ENC[AES256_GCM,data:OmPOT3J/0geG+DaJ28KoQ0e2NmXvrdheae4LG0dt47uJX7bQ0BaDIBEOPizjF1rDJotnv658KzMuiVS05RqVebk2xgnt9EPDT1DlnVR4kkUsH6Cx5WSBBzhb+zfHAkxACsz2bXJgOF7pb/UzD6ePAAbmLh6GdQQt9X3NDAR9P/s=,iv:DydH7Mido67wv3VF/7l7w8uTXgqPlxLa8n74C3j4pIU=,tag:n2/7uvdpXPDfl67cZ1+2rA==,type:str]
    pgp:
        - created_at: "2025-11-11T02:27:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAAkU9AS1Hhg+8QhICuLfozsoKOduOiumY3lJNHjvPHB0jC
            wjNeLOiTAPdgy19waGMVdiWGPAKy2B69WWZl2ZBqX9fLhrqU0nCEv1areO9zjjyz
            fHbmxm4QM6PLbooIk6pD9dGB+nZVfrZJE4CzaOl7AmnzYBmFpK8mcDX4MHmLrO8j
            SiO8fjy5ZtpCWBQRLuJv3QTPBU9cGMSGAWlsweujlsvBhk1yqFvXB8fQQQjDTCX+
            gemB/yrjf/bcFGnp4LZIH1ZNBSFC4IDb8PJ5UBDZUKzfjjP6Vvpl4YuJmAKTNc7+
            yT+lewbL/5B0792WVYg0afOPKkh8J5quzl5d1kH6iItRmDbAhTBuAInrzCVPDpTl
            NKpMIfI7Q6tYqEqB3OqTF7bvC73ltOzSfOPdyKIiLuhAphuq50YUzqYfP87N7wAF
            DfRQDdk6SaCPKM4mNfi2ZDfyLn3l1FA0LbEXOUjvJRuOT53xms4OST1qAeSYMWC9
            w+tVqwMumYmuQGVD8zjoBbjPeHzH7i0S8yfLROOpVSc/p8S0GQ8heN4H7ej/uR2M
            x7wc6IJWYbdisa2u+MCaFEXpsgMvsoo76EMyeJtbubSDA90chIsR+ja7PvNb+VGX
            L0Nl7wvWOkeztd1mTCJmazv1FKlDpsLbNDhEtYco50zn/KkuBfinRoS9U1KzyajS
            XgHb4Q98Zb9n6Z0YpI4lXEA+fydMM9lZapYnRLdTlGHozo7XmSqX1VsYuY7SCTlg
            gk8VC33mnOO7eQfSQL7AjYXTAXqC6ZduKhR7E/iHAODYwA7QRTu1yOCjV498nOo=
            =NDZl
            -----END PGP MESSAGE-----
          fp: A2AF5A4B747411B2D6B9331CFA018F24752F2F6E
    unencrypted_suffix: _unencrypted
    version: 3.11.0
