api_encryption_key: ENC[AES256_GCM,data:xD+GmE/BJ8bCDEOb2HadZKvrj66vDo732wlDRmsBF3MkUYJDBqaqEX6mHZk=,iv:o+IoXNW7wVhoXDowgZD8qWu9QlMNhFeDGkSVZPgUv3E=,tag:92QTDbR3NB7Hc1A+TJUN9w==,type:str]
ota_password: ENC[AES256_GCM,data:mxTbC6drAer6Kq2U3T8v0w==,iv:m5Ir5kX/3KW1OPj3hKblVowkf9Goe7MjjUTBBoCLgkc=,tag:GUhigw2XNR4MUtBU9cMz6w==,type:str]
wifi_ssid: ENC[AES256_GCM,data:/GyS5AJyzvVeWQJKYe62Yjo=,iv:rmDYTNCYP+Q5zhH3UcImBqjIO22CpGF6wAA5TRaDFF4=,tag:F61KMBuqM0Bm/sC2yJpVAg==,type:str]
wifi_password: ENC[AES256_GCM,data:ZtKgu7RSdRyoVUn8qP9tNFJ3pcXhm566ztY=,iv:4fwWVxJgmtkAQDNoB857OZcx2nzyY7ebdbw4d7AVmWo=,tag:7LpK3dh+xHyxr/qmemkIkQ==,type:str]
led_node_2_ip: ENC[AES256_GCM,data:2+RW1jgsRZItrg==,iv:1OnEaatCRQLWUCgn2Krz1/YcsTgxYYJfefaZC1fT9NI=,tag:BdVVURQNrqPCibE6mn+ljA==,type:str]
ir_blaster_ip: ENC[AES256_GCM,data:bYvLfDXwnauR7w==,iv:+iqXRJV3/SOWmJ1Uv0QZBSPQdWhSsJYkte5HVTYK/C4=,tag:oK4k4LGY2GGSLwRmSWG5gw==,type:str]
ir_blaster_2_ip: ENC[AES256_GCM,data:J//9suUHVd9h+g==,iv:xK9WJlDmYMfh1b/kWTl8TSjzDgwuik3ltTpR712hQrw=,tag:1/fQNupIJKLahRuhRGa/Ow==,type:str]
ir_blaster_3_ip: ENC[AES256_GCM,data:/wyAHRthgpKA,iv:dNudp34IuBZXj/SyWEln8mKsixlRmDzU57e9LWWO91M=,tag:JigDedEa+JGkT4sKuHFO7Q==,type:str]
led_dimmer_node_1: ENC[AES256_GCM,data:RVRHY4EJs1Kt+Q==,iv:JlEaTZbsOhzJNWfIt3VFyAoW/r6z8NucJleqTtqRdRI=,tag:vJbqBeizA5dZuss9NngzJA==,type:str]
artnet_local_ip: ENC[AES256_GCM,data:/5UA+crwx3M6bw==,iv:OH20q0e0bJGr8RSjoXITlaaqfjYIoB91cCqiuCwmhpo=,tag:DlS1x4dIIGHUdpJlZKUQhw==,type:str]
sound_thermometer_test_local_ip: ENC[AES256_GCM,data:7hOg6n6zYZ2Dug==,iv:hA4bLH5J6ScXwmf/4TVZHQFATnsluhCuP+oM3zM6o1c=,tag:3ScLeR/x8JsVUEM03oWgyg==,type:str]
sound_thermometer_local_ip: ENC[AES256_GCM,data:VmV6IndSbXKGqQ==,iv:LECfpR9aNywa5ye1gt7OWcX6W3UbArHiCTOOS++7idQ=,tag:ge2kTMgnaKzstRAxDGNhmw==,type:str]
moisture_sensor_1_ip: ENC[AES256_GCM,data:tPpz10CqY3kx,iv:GRqmmR9mz1xCc2f4U7MUW/zedL39t0KkkywMSMHjW64=,tag:3Sw0jmi6x4vpGAfy+3zVPg==,type:str]
metronome_ip: ENC[AES256_GCM,data:sEkObmJkskKb0Q==,iv:xRVgRpA1PNlt1TcEULnYmlydW1xEzQfQBFfhgLO9Ycw=,tag:BslMcNShYM+yviknlTCG6w==,type:str]
pixel_hotspot_ssid: ENC[AES256_GCM,data:wfN4Fu61UvHh1A==,iv:n/pPn4cUFhN2hX/LaHJUXlCmUFVxubJ/SU8TQxXRpOw=,tag:Q39A3sdwwM1JLbYrSm8p2A==,type:str]
pixel_hotspot_password: ENC[AES256_GCM,data:M5aYs3QT9YifplTf,iv:1noBDuAXYN1vjcwf0XtJae+ekT7FDkw3W5wlynotNaI=,tag:TOs4o8DfMXYnEWRPwTGpRQ==,type:str]
travel_router_ssid: ENC[AES256_GCM,data:YHIo7acVBfpCttUA2K8H5bI=,iv:0jLER9x68i7yF9HZnt08Ip8TuP0r6ey98iD3o2UZ4Y8=,tag:p5C/B3EfGkx6AYz7dbtNcA==,type:str]
travel_router_password: ENC[AES256_GCM,data:zkpx4hckoV78sGYa/2U=,iv:e1AORijELqiuWCQ2hDutIUz1/YWXwKrurVIbSxZMr2E=,tag:4D5Zq2k04suUSPvatTvg1A==,type:str]
zhenya_hotspot_ssid: ENC[AES256_GCM,data:MR5mLUY=,iv:sv7URNC6h7AAxXXai56sNW8H6+f5GCKSn6jc87xwqSo=,tag:6b19ujjMDRK11V+oA0jJRA==,type:str]
zhenya_hotspot_password: ENC[AES256_GCM,data:S5/UD6GN7JAF8UT+,iv:4qxliU/dcTfCVRUoCL7i8S+2AivdCdqluWQ+8ixYDis=,tag:t9DzzEMq5UIzDdgZJY5Jmw==,type:str]
web_server_username: ENC[AES256_GCM,data:FEyKsoY=,iv:aWabfHTcAy/GQ0p87GgmZ+D1+/OFvpdAs/El2TU+hFw=,tag:2OWyGdEA1kIzBsHZpH2hww==,type:str]
web_server_password: ENC[AES256_GCM,data:srtKuvmg/1E9Zg==,iv:X2nt/9NEUVgrPAlVTmMCBjnT3Q6sQUcbIjz2+hbTWwg=,tag:NiEI52QQSOvkwV7x7WXWtQ==,type:str]
ap_password: ENC[AES256_GCM,data:LDVSP+FhUFUv8A==,iv:inqzBZN0cROsUk27fsDI3ieZLFtUHyLADpjTedAbVno=,tag:4oQVgvfksan/3qVx5NX70g==,type:str]
sops:
    lastmodified: "2025-12-06T21:23:42Z"
    mac: ENC[AES256_GCM,data:R90XIAP2uISUpjGsS/yMYZgYlJyB2m3COgJTc9vPnPd3u7JS1Y8DZyDqKAOYMDYT7eQSOT46zAs6/32bDrLTgV8TdEs0pslcGZei3Nqe3dNttENFMQ5mZuLT1tS2rkL7kEhQrAH3qAAiJR/jysqviSElVykmrmalQboko+kgJM8=,iv:dGUUcOlmgiadBAGF1KEomZy02nqvQ+BU/xbdT6qICjM=,tag:YqGVd/xOq3BO2G6ZbtvTRQ==,type:str]
    pgp:
        - created_at: "2025-12-06T21:23:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/8CfVZ6hiIleR3/EvcPwQgUlDZvvxChENN78qabktpDr/R
            +8cHFn9em2KJvOIVNucULZvN3uEo45mNNoLscn1sFZHk/anxgqof4OpAoJiNaMyU
            a53p6Fa0Ouva9pjqAWbcwCTP9RLphbZTxt5uz+nf2/IBhci2cz4hHz18iOcCf/nm
            7gpkXVBeelXkS/NfdepILqMjbkOm6/t87vcIquF0decA/OD+L8KKwQnHkUNF/g9l
            Wct7A9EaF52EM7RG/MQZKej3zUT8co3I5h8/BjFLzSP4kn+CD15d6VbP3KQtukTB
            ZEC6waCeoRPrH11psNQ3zq1kCoxx30q+hhB5YyQNMTy6zmqpie1iTUE8KEuDc783
            GOy/V+m5BWqr1rYAlEbmJNjdsgBJXN5SNwSQHrTfuYjSuUDLSEo8GKqIJC0QSYiU
            JwxFBEVHXjxnG6UKaMsAnnHaSLZBq58UZXBZ/mkxuV9jf6KJYvGqkwNRmPrNps1p
            DIIUgFhkamhbrG+iN0bk3Fw3iDvD1WUIjsOMGr26buGNUegR3W5IvaOHcqXgRdKl
            wUHUN9j4bf1D2WEmUiF3Me4PwOx78r1wKEPYKaca1xeo2n5C7YRR03a6Nbl39o61
            Nz4dtCJu7tNH4TaHbu4qyPOpqgInvv//BOrI84gvPGmrmFMELolYCgeDh/I1S3PS
            XgGmN03Kjmc7OEc0e1d24nTTXuil7ThjVHnZgrz6X/mOv38NNz38TiTbr7IGHauI
            9p2c4vRknIZ0grZRCGevBcgpjDr+KGn/vroQk+swzvkY7ZtZwVaYzLnYoO+eUpk=
            =/NGR
            -----END PGP MESSAGE-----
          fp: A2AF5A4B747411B2D6B9331CFA018F24752F2F6E
    unencrypted_suffix: _unencrypted
    version: 3.11.0
