api_encryption_key: ENC[AES256_GCM,data:5dtWGmIp6izaeCUZeCF1Waq7hBnPskZ+bDXhwAIR7L4EYoRm8KsBMrkZm10=,iv:ihxgrhtj+cdeOIBfo0nzJ4kg8McpHYRHccOFSh1EP1s=,tag:6faKXTFwZWZFw9OdvKnkAw==,type:str]
ota_password: ENC[AES256_GCM,data:jmUS8yMjn8koZHayXc6bfw==,iv:Kl7v9wQyPHoCV5DF22utCSq/qsvS0HiHkQnNn3RLuNc=,tag:kT/I9aFO+9U3Bq0QVAlQVQ==,type:str]
wifi_ssid: ENC[AES256_GCM,data:Fw7Hs+26Jpy+fpcSrwhvdh8=,iv:MiBELxaBuNqmrvbwghM6RwqrlJ6zKscsn8OitCcZa4k=,tag:qMZLbfd6mOgjwfY8ZpjF5A==,type:str]
wifi_password: ENC[AES256_GCM,data:R/a89YZ8xv6HSbrP7MtrGKC1qH9HhsnIMdk=,iv:hxoDYnzXF5nb75EX/2TgaoY3KhrHJdxWp24nvMMn8kM=,tag:SiUMBZxoqsHNiCIUxT51EQ==,type:str]
led_node_2_ip: ENC[AES256_GCM,data:c8xdaQqankMlSg==,iv:yUjFQWjq0ZqsxpxJBNu5HBXt5ZBMxGFP1aF033RQM+k=,tag:QeRwQQTA8PxElML8zz5cZw==,type:str]
ir_blaster_ip: ENC[AES256_GCM,data:RzYNkDywI3JQWw==,iv:UeNzk/qlG60meuwJNz6lDGvQHUBKD8SlgEF24IXHK1Y=,tag:JJKezqwkmNAifCV6pCAC5Q==,type:str]
ir_blaster_2_ip: ENC[AES256_GCM,data:vQbhptLIrL0+TA==,iv:uAGLcxxVQTvz0+7njwCg3OYNKS5fLCyeb4dL3nWQlLk=,tag:gtvqFJiO4kTsUh1Lq6qd3w==,type:str]
ir_blaster_3_ip: ENC[AES256_GCM,data:uZxGb2NUJCX2,iv:b115E7NjlIklx1ebvX2B+TbxBQby7WXsko+nlbZgu1M=,tag:+JQqJTbWeo2fWEYKTNj+YA==,type:str]
led_dimmer_node_1: ENC[AES256_GCM,data:Fy9YN5j0o6PWPw==,iv:cEV9yGK2nWaJyii/EG22UJVD4y36TZGoHbc86RT7SoI=,tag:4Mq4EhpjLg9gOWjq/BCWrg==,type:str]
artnet_local_ip: ENC[AES256_GCM,data:NYtmuFMWrhqxDg==,iv:dwRx5CZnQRtFXFhjL3Zd59Xi9Z35zyDhA4IZuRbS9LA=,tag:IpTBzunQArjknhlr+QRcgw==,type:str]
sound_thermometer_local_ip: ENC[AES256_GCM,data:PRJ8G24mCBz3YA==,iv:hTCtpUM1MHqUJnSikEntnFYlj1RHCW3bUIMNYJg6Rsc=,tag:k8sW20QSWftrb7bUXbxiNg==,type:str]
moisture_sensor_1_ip: ENC[AES256_GCM,data:mIPgJdvLTqFu,iv:5m1cmEm0UHgWWeb5Tx7fpi96CyLkuuRTVh8rtuw2PNE=,tag:Wnx9R1Kn41j9ECZq9OQ0jQ==,type:str]
metronome_ip: ENC[AES256_GCM,data:xYfc0aXXywyUMQ==,iv:dF3SBpz5BDrO9sSe1zPXPSW1vhSMos9n/M4mUJudLEQ=,tag:5/KJOm+vRwBwMlvKjSOg7w==,type:str]
pixel_hotspot_ssid: ENC[AES256_GCM,data:MJ+vhsT7FSwxXQ==,iv:ebT80VAmN/x9g5vfuyhYKdHMn4Qtmx6Hf8qRAvbY794=,tag:rFh4M455wCGOuqLFo/A+3Q==,type:str]
pixel_hotspot_password: ENC[AES256_GCM,data:rup7E/ekd/iEXNFz,iv:NGKvZsG1h27FUtBJ1C3hK1SHRH44hD2hU0r4c2x1myU=,tag:jgou5BSCiQtjNcrZ8+YNMg==,type:str]
travel_router_ssid: ENC[AES256_GCM,data:NGrHICmPgvGHyJrkTCFJqMA=,iv:Zrz0/joEA4jh+se+frOmQ0So8+2Dxf0/c1SpWgsaJNg=,tag:4/jwnGj2dXUDT4ybTI0CJQ==,type:str]
travel_router_password: ENC[AES256_GCM,data:5kIc8S7nWtjufwkDHsI=,iv:CVGwkv5hZorcduRQ6I58Yf6au8oXDBFOOfFezMv+aM0=,tag:9fzqZfNw37gOt7bytYAJKQ==,type:str]
zhenya_hotspot_ssid: ENC[AES256_GCM,data:5aABV6c=,iv:KSYQ7wGP95445umsf7CdmkExHWQlKm2MUgddDSM7Qp4=,tag:KywKqrTm9Oa0uomnA7zCeg==,type:str]
zhenya_hotspot_password: ENC[AES256_GCM,data:PhDAbm5diKhmlXRg,iv:r2fEsCUc9n55eh7OlfnLjPMMvEVw8gJrdxqcjaMP29c=,tag:rb5qDdsqWkiF1H8iL6cjMg==,type:str]
web_server_username: ENC[AES256_GCM,data:XJh3L8I=,iv:cx82y4x8QjdX1i4GbtCq2M2I+9EbblFVzDxCrmTWd04=,tag:laKTlTiTebw46pHV2xxslw==,type:str]
web_server_password: ENC[AES256_GCM,data:qaBbX83BU3xASaENn9/+8wOb,iv:0m+ZQ2o5AKEzf6gsi7pVKxBPJx65JFOV4hxePh3dYYQ=,tag:lIVgLXCvjSvux91Fx1cEiw==,type:str]
sops:
    lastmodified: "2025-11-21T08:59:43Z"
    mac: ENC[AES256_GCM,data:iPlYZcjADwtVCPTW2gvbqYlItXRnc1cf2GBGmrbTkHTwdhs4AEGX34807Dja5jMTN3YZcfOXgOgxPoJHN02wIJinjx2BtVRVIA8UYAwfRDyaIru0In/ANVm8t1I2GYC12KZBPZ3X8bawDsmhzghbReoh1ook5WchaaDQQRzwR5c=,iv:4OsCGcl4k7fZSnhoFTnOH9IzIliorqrBN/4/kLqAdLA=,tag:Ly8ydCQGj4a7B8WFQIvkmA==,type:str]
    pgp:
        - created_at: "2025-11-21T08:59:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//XNd4SJAkAuO+ZrrHyJd3kFrMKcbldYejEdNkY7nsXhHV
            vQO1ZsIT5ecm6g2GC07qGAbHmOO6qI+qWXfMcXXNlWG7HXq4MI8G8qB6U//CuA6x
            SuNpc5Z7vMZWxF5CttWavnqjVImGN0ylBLVdHeZlzQruZ3tgSgfJyZTpXVd9eo9N
            vjYOzycFbp6+J3q/EdRvi915pXijxZKJUvdJBJVf1MdwZymrhmdiNMGnR7NAO0oU
            1IyZyumX4y/rOK7IX6nWKH9RoXqiTg1cYZciQfR7oZm1jgs+eNf7+Sc7wJYgKmme
            MBazES2OyQmBhJB8+o0LdUXDuu+ssMhpow9cLgvfcSTuvY6dp076cpSKsDL1wVmq
            6qewAxlehiw1HEXRQyeBjPEb2tGdtXq5Dvg/rqfKMEMtqU2CuGF1Kh6/Mgorb2fg
            VHJGN+yLUxyVfKnbk01nNnOE++2UKmJPTI8MppXMVMnLvlQDacPU3QLPza22TaXL
            yMe4jBBCakrgJe4HuVjl77K09lQVC5pPu4jCl1vn+Ei/YGB8aEqfB/EHXefIMFhc
            N3EaXQL3lQUGOLHDG1QG9NVW3V+NYeS5Hm6m93zudN1Dvfs0IgosdcMxdY6KHz3t
            Uu8AFJBHs4N8M+2mcYsmFz0ArmXLhSB489w2XpGSsoDGEODvoZgNAi2TKKaRVALS
            XgEkwPdQR4h23qk3IUR0UJjVUTNPRlL28l6ymsTj1RePeC5IOUHBdkFgs1rqBD4a
            8RGLtkcoe6MEdTWI7/cDbOMqzCCEdsXnYIm/1e4U3XIAIapuAqGSh666zKAbhV0=
            =RRmU
            -----END PGP MESSAGE-----
          fp: A2AF5A4B747411B2D6B9331CFA018F24752F2F6E
    unencrypted_suffix: _unencrypted
    version: 3.11.0
